version: "3.9"

services:
   nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - web-network


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zhh123
    networks:
      - web-network

  blog-node:
    image: zhaohuinan/blog-node:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zhh123
    networks:
      - web-network

networks:
  web-network:

